# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for AgentForensics Desktop Launcher
# Build: pyinstaller agentforensics_launcher.spec

a = Analysis(
    ['launcher.py'],
    pathex=['.'],
    binaries=[],
    datas=[
        ('agentforensics/dashboard/ui.html', 'agentforensics/dashboard'),
    ],
    hiddenimports=[
        'agentforensics',
        'agentforensics.dashboard',
        'agentforensics.dashboard.server',
        'agentforensics.cli',
        'agentforensics.tracer',
        'agentforensics.classifier',
        'agentforensics.alerting',
        'agentforensics.fingerprinter',
        'agentforensics.reporter',
        'agentforensics.semantic',
        'agentforensics.store',
        'agentforensics.models',
        'agentforensics.differ',
        'agentforensics.integrations',
        'agentforensics.mcp_server',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'fastapi',
        'httpx',
        'httpx._transports',
        'httpx._transports.default',
        'click',
        'rich',
        'rich.console',
        'rich.table',
        'pydantic',
        'pydantic.v1',
        'multiprocessing',
        'sqlite3',
        'webview',
        'webview.platforms',
        'webview.platforms.winforms',
    ],
    hookspath=[],
    runtime_hooks=[],
    excludes=['torch', 'transformers', 'datasets', 'sklearn'],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AgentForensics',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    icon=None,
    onefile=True,
)
